### ISSUE TITLE
有一个小发现

### ISSUE THREAD

**Issue by MrPsCHen** [monoplasty/vue3-slide-verify#1]
当imgs传本地路径时，确保图片路径是否正确。建设传oss上的图片地址
这句话中 “建设”
我猜测是  “建议”
无伤大雅~

**Comment by monoplasty** [comment]
> 当imgs传本地路径时，确保图片路径是否正确。建设传oss上的图片地址 这句话中 “建设” 我猜测是 “建议” 无伤大雅~

感谢细心的你发现了这个问题，欢迎共创！！谢谢谢你
