### ISSUE TITLE
使用报错 页面加载不出来

### ISSUE THREAD

**Issue by Lvna5** [monoplasty/vue3-slide-verify#4]
![image](https://user-images.githubusercontent.com/37654806/187640975-cea3f5fa-b6a1-40f1-ab9f-c4c590ce6013.png)
![image](https://user-images.githubusercontent.com/37654806/187640994-12bb86ae-048e-4893-8de4-2678e9bf0999.png)

您好 我这直接用的demo出现如上问题，麻烦帮忙处理下

**Comment by monoplasty** [comment]
>  你好，你这个不是报错。这个是vue 给的警告。 页面其实已经出来了。 只是滑块的背景图没有加载出来。 图片加载不出来是因为图片使用的这个api： https://picsum.photos/ 这个网站是国外的，访问较慢，可能的原因的网络问题。可以参考 https://github.com/monoplasty/vue-monoplasty-slide-verify/blob/master/src/App.vue  这个文件的写法，采用本地的图片。

**Comment by Lvna5** [comment]
是的 页面是已经出来了 样式没有出来 包括我给了本地的图片 也不出来
![image](https://user-images.githubusercontent.com/37654806/187655055-e00256ca-8747-4689-af38-189886c5039e.png)
![image](https://user-images.githubusercontent.com/37654806/187655070-814f97cc-cf86-4344-a38f-9bdb7a8544f5.png)

**Comment by Lvna5** [comment]
> > 你好，你这个不是报错。这个是vue 给的警告。 页面其实已经出来了。 只是滑块的背景图没有加载出来。 图片加载不出来是因为图片使用的这个api： https://picsum.photos/ 这个网站是国外的，访问较慢，可能的原因的网络问题。可以参考 https://github.com/monoplasty/vue-monoplasty-slide-verify/blob/master/src/App.vue  这个文件的写法，采用本地的图片。

页面是已经出来了 样式没有出来 包括我给了本地的图片 也不出来

**Comment by monoplasty** [comment]
最好把你使用的相应环境，还有报错信息，和部分对应代码一起发出来哈，这个方便定位问题在哪。看图片没有出来的话，可能是图片引用路径问题。 看看有没有相应报错信息，这样可以快速排查问题
