### ISSUE TITLE
默认的第三方图片地址无法访问

### ISSUE THREAD

**Issue by JohnsonzZQAQ** [monoplasty/vue3-slide-verify#5]
![image](https://user-images.githubusercontent.com/42951741/188776259-fb265200-10f9-46aa-b4ee-8818ff833859.png)
一直 跨域
但开梯子可以就可以正常访问，被墙了？

**Comment by monoplasty** [comment]
你好，组件中使用了第三方的随机图片api， 该获取到的图片现已无法免费使用。 现已更换一个新的图片源（已更新到版本v1.1.4，更新即可）。但无法保证该图片源能长期维护使用。强烈建议使用 自己的cdn链接来保证图片资源的可用性！！ 代码案例也使用了 本地图片路径使用的方法。
